### ISSUE TITLE
add IP Address Tracker 

### ISSUE THREAD

**Issue by ananyag309** [Kushal997-das/Project-Guidance#1589]
### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

This is a solution to the IP address tracker challenge on Frontend Mentor it should be helpful in many ways for tracking the IP Address

Users should be able to:

View the optimal layout for each page depending on their device's screen size
See hover states for all interactive elements on the page
See their own IP address on the map on the initial page load
Search for any IP addresses or domains and see the key information and location

![image](https://github.com/user-attachments/assets/d2f8f3ba-b09a-4e04-ba96-5195e95544e2)

### 🔍 Priority Level
- [x] High
- [ ] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________
